homework course 8 test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -152,6 +152,22 @@ jobs:
         with:
           ssh-private-key: ${{ secrets.SSH_KEY }}
 
+      - name: Install docker-compose on server
+        run: |
+            ssh -o StrictHostKeyChecking=no \
+                ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
+              if ! command -v docker-compose &> /dev/null; then
+                echo 'docker-compose not found. Installing...'
+                sudo apt update
+                sudo apt install -y docker-compose
+              else
+                echo 'docker-compose already installed'
+              fi
+            
+              docker-compose --version
+              echo 'docker-compose installation verified'
+            "
+
       - name: Prepare environment on server
         run: |
           ssh -o StrictHostKeyChecking=no \
@@ -169,6 +185,7 @@ jobs:
             CELERY_RESULT_BACKEND=redis://redis:6379/0
             EOF
           "
+
       - name: Deploy application
         run: |
           ssh -o StrictHostKeyChecking=no \
